// Free Dictionary API - 免费获取单词释义和音标
const DICTIONARY_API = 'https://api.dictionaryapi.net/api/v3/entries/en'

/**
 * 获取单词基础信息（释义 + 音标）
 * @param {string} word - 单词
 */
export async function fetchWordDetails(word) {
  try {
    const response = await fetch(`${DICTIONARY_API}/${encodeURIComponent(word.toLowerCase())}`)
    if (!response.ok) throw new Error('API response not ok')

    const data = await response.json()
    console.log('Dictionary API 返回:', data)

    if (!Array.isArray(data) || data.length === 0) {
      // 如果 API 没有返回数据，尝试使用本地词典
      return getLocalDefinition(word)
    }

    const entry = data[0]
    const phonetic = entry.phonetic || entry.phonetics?.[0]?.text || ''
    const meanings = entry.meanings || []

    // 提取释义
    const definitions = meanings.map(m => {
      const partOfSpeech = m.partOfSpeech || 'n.'
      const defs = (m.definitions || []).slice(0, 3).map((d, i) =>
        `${i + 1}. ${d.definition}`
      ).join('\n')
      return `【${partOfSpeech}】\n${defs}`
    }).join('\n\n')

    return {
      phonetic: phonetic || '',
      definition: definitions || '暂无释义'
    }
  } catch (error) {
    console.error('Dictionary API Error:', error)
    // 使用本地离线词典作为后备
    return getLocalDefinition(word)
  }
}

/**
 * 本地离线词典 - 常见物品的中英文对照
 */
const localDictionary = {
  // 常见物品
  'phone': { phonetic: '/foʊn/', definition: '【noun】\n1. 电话；手机\n2. 听筒' },
  'cell phone': { phonetic: '/sel foʊn/', definition: '【noun】\n1. 手机；移动电话' },
  'telephone': { phonetic: '/ˈtelɪfoʊn/', definition: '【noun】\n1. 电话\n2. 电话机' },
  'charger': { phonetic: '/ˈtʃɑːrdʒər/', definition: '【noun】\n1. 充电器\n2. 收费者' },
  'cup': { phonetic: '/kʌp/', definition: '【noun】\n1. 杯子\n2. 茶杯\n3. 奖杯' },
  'bottle': { phonetic: '/ˈbɑːtəl/', definition: '【noun】\n1. 瓶子\n2. 酒' },
  'book': { phonetic: '/bʊk/', definition: '【noun】\n1. 书；书籍\n2. 账簿\n【verb】\n1. 预订' },
  'computer': { phonetic: '/kəmˈpjuːtər/', definition: '【noun】\n1. 电脑；计算机' },
  'laptop': { phonetic: '/ˈlæptɑːp/', definition: '【noun】\n1. 笔记本电脑；手提电脑' },
  'keyboard': { phonetic: '/ˈkiːbɔːrd/', definition: '【noun】\n1. 键盘\n2. 电子琴' },
  'mouse': { phonetic: '/maʊs/', definition: '【noun】\n1. 老鼠\n2. 鼠标' },
  'chair': { phonetic: '/tʃer/', definition: '【noun】\n1. 椅子\n2. 席位' },
  'table': { phonetic: '/ˈteɪbəl/', definition: '【noun】\n1. 桌子\n2. 表格' },
  'clock': { phonetic: '/klɑːk/', definition: '【noun】\n1. 时钟\n2. 计时器' },
  'bed': { phonetic: '/bed/', definition: '【noun】\n1. 床\n2. 河床\n3. 花坛' },
  'door': { phonetic: '/dɔːr/', definition: '【noun】\n1. 门\n2. 门口' },
  'window': { phonetic: '/ˈwɪndoʊ/', definition: '【noun】\n1. 窗户\n2. 窗口' },
  'car': { phonetic: '/kɑːr/', definition: '【noun】\n1. 汽车\n2. 车厢' },
  'bicycle': { phonetic: '/ˈbaɪsɪkəl/', definition: '【noun】\n1. 自行车\n2. 脚踏车' },
  'bus': { phonetic: '/bʌs/', definition: '【noun】\n1. 公共汽车\n2. 巴士' },
  'train': { phonetic: '/treɪn/', definition: '【noun】\n1. 火车\n2. 列车\n【verb】\n1. 训练；培训' },
  'apple': { phonetic: '/ˈæpəl/', definition: '【noun】\n1. 苹果' },
  'banana': { phonetic: '/bəˈnænə/', definition: '【noun】\n1. 香蕉' },
  'orange': { phonetic: '/ˈɔːrɪndʒ/', definition: '【noun】\n1. 橙子；橘子\n2. 橙色' },
  'water': { phonetic: '/ˈwɔːtər/', definition: '【noun】\n1. 水\n【verb】\n1. 浇水；灌溉' },
  'coffee': { phonetic: '/ˈkɔːfi/', definition: '【noun】\n1. 咖啡' },
  'tea': { phonetic: '/tiː/', definition: '【noun】\n1. 茶\n2. 茶叶' },
  'milk': { phonetic: '/mɪlk/', definition: '【noun】\n1. 牛奶\n2. 奶制品' },
  'bread': { phonetic: '/bred/', definition: '【noun】\n1. 面包' },
  'egg': { phonetic: '/eɡ/', definition: '【noun】\n1. 鸡蛋\n2. 蛋' },
  'rice': { phonetic: '/raɪs/', definition: '【noun】\n1. 米饭\n2. 大米' },
  'fish': { phonetic: '/fɪʃ/', definition: '【noun】\n1. 鱼\n2. 鱼肉' },
  'meat': { phonetic: '/miːt/', definition: '【noun】\n1. 肉\n2. 肉类' },
  'chicken': { phonetic: '/ˈtʃɪkɪn/', definition: '【noun】\n1. 鸡肉\n2. 鸡\n3. 小鸡' },
  'dog': { phonetic: '/dɔːɡ/', definition: '【noun】\n1. 狗\n2. 犬' },
  'cat': { phonetic: '/kæt/', definition: '【noun】\n1. 猫\n2. 猫科动物' },
  'bird': { phonetic: '/bɜːrd/', definition: '【noun】\n1. 鸟\n2. 鸟类' },
  'flower': { phonetic: '/ˈflaʊər/', definition: '【noun】\n1. 花\n2. 花朵' },
  'tree': { phonetic: '/triː/', definition: '【noun】\n1. 树\n2. 树木' },
  'sun': { phonetic: '/sʌn/', definition: '【noun】\n1. 太阳\n2. 阳光' },
  'moon': { phonetic: '/muːn/', definition: '【noun】\n1. 月亮\n2. 月球' },
  'star': { phonetic: '/stɑːr/', definition: '【noun】\n1. 星星\n2. 恒星\n3. 明星' },
  'cloud': { phonetic: '/klaʊd/', definition: '【noun】\n1. 云\n2. 云朵' },
  'rain': { phonetic: '/reɪn/', definition: '【noun】\n1. 雨\n【verb】\n1. 下雨' },
  'snow': { phonetic: '/snoʊ/', definition: '【noun】\n1. 雪\n【verb】\n1. 下雪' },
  'book': { phonetic: '/bʊk/', definition: '【noun】\n1. 书\n2. 书籍\n【verb】\n1. 预订' },
  'pen': { phonetic: '/pen/', definition: '【noun】\n1. 笔\n2. 钢笔' },
  'pencil': { phonetic: '/ˈpensəl/', definition: '【noun】\n1. 铅笔' },
  'bag': { phonetic: '/bæɡ/', definition: '【noun】\n1. 包\n2. 袋子' },
  'hat': { phonetic: '/hæt/', definition: '【noun】\n1. 帽子' },
  'shoe': { phonetic: '/ʃuː/', definition: '【noun】\n1. 鞋子\n2. 鞋' },
  'glass': { phonetic: '/ɡlæs/', definition: '【noun】\n1. 玻璃\n2. 玻璃杯\n3. 眼镜' },
  'mirror': { phonetic: '/ˈmɪrər/', definition: '【noun】\n1. 镜子' },
  'toothbrush': { phonetic: '/ˈtuːθbrʌʃ/', definition: '【noun】\n1. 牙刷' },
  'towel': { phonetic: '/ˈtaʊəl/', definition: '【noun】\n1. 毛巾\n2. 手巾' },
  'soap': { phonetic: '/soʊp/', definition: '【noun】\n1. 香皂\n2. 肥皂' },
  'shampoo': { phonetic: '/ʃæmˈpuː/', definition: '【noun】\n1. 洗发水\n2. 香波' },
  'television': { phonetic: '/ˈtelɪvɪʒən/', definition: '【noun】\n1. 电视\n2. 电视机' },
  'remote': { phonetic: '/rɪˈmoʊt/', definition: '【noun】\n1. 遥控器' },
  'refrigerator': { phonetic: '/rɪˈfrɪdʒəreɪtər/', definition: '【noun】\n1. 冰箱' },
  'air conditioner': { phonetic: '/er kənˈdɪʃənər/', definition: '【noun】\n1. 空调\n2. 空气调节器' },
  'fan': { phonetic: '/fæn/', definition: '【noun】\n1. 风扇\n2. 扇子\n3. 粉丝' },
  'lamp': { phonetic: '/læmp/', definition: '【noun】\n1. 灯\n2. 台灯' },
  'umbrella': { phonetic: '/ʌmˈbrelə/', definition: '【noun】\n1. 雨伞\n2. 伞' },
  'watch': { phonetic: '/wɑːtʃ/', definition: '【noun】\n1. 手表\n2. 观看\n【verb】\n1. 观看\n2. 注视' },
  'wallet': { phonetic: '/ˈwɑːlɪt/', definition: '【noun】\n1. 钱包' },
  'key': { phonetic: '/kiː/', definition: '【noun】\n1. 钥匙\n2. 关键\n【verb】\n1. 键入' },
  'card': { phonetic: '/kɑːrd/', definition: '【noun】\n1. 卡片\n2. 信用卡' },
  'money': { phonetic: '/ˈmʌni/', definition: '【noun】\n1. 钱\n2. 货币' },
  'camera': { phonetic: '/ˈkæmərə/', definition: '【noun】\n1. 相机\n2. 摄像机' },
  'photo': { phonetic: '/ˈfoʊtoʊ/', definition: '【noun】\n1. 照片\n2. 图片' },
  'paper': { phonetic: '/ˈpeɪpər/', definition: '【noun】\n1. 纸\n2. 纸张\n3. 报纸' },
  'newspaper': { phonetic: '/ˈnuːzpeɪpər/', definition: '【noun】\n1. 报纸' },
  'magazine': { phonetic: '/ˈmæɡəziːn/', definition: '【noun】\n1. 杂志\n2. 期刊' },
  'notebook': { phonetic: '/ˈnoʊtbʊk/', definition: '【noun】\n1. 笔记本' },
  'desk': { phonetic: '/desk/', definition: '【noun】\n1. 书桌\n2. 办公桌' },
  'sofa': { phonetic: '/ˈsoʊfə/', definition: '【noun】\n1. 沙发' },
  'pillow': { phonetic: '/ˈpɪloʊ/', definition: '【noun】\n1. 枕头' },
  'blanket': { phonetic: '/ˈblæŋkɪt/', definition: '【noun】\n1. 毯子\n2. 毛毯' },
  'television': { phonetic: '/ˈtelɪvɪʒən/', definition: '【noun】\n1. 电视（机）' },
  'radio': { phonetic: '/ˈreɪdioʊ/', definition: '【noun】\n1. 收音机\n2. 无线电' },
  'music': { phonetic: '/ˈmjuːzɪk/', definition: '【noun】\n1. 音乐' },
  'headphone': { phonetic: '/ˈhedfoʊn/', definition: '【noun】\n1. 耳机\n2. 头戴式耳机' },
  'battery': { phonetic: '/ˈbætəri/', definition: '【noun】\n1. 电池' },
  'cable': { phonetic: '/ˈkeɪbəl/', definition: '【noun】\n1. 电缆\n2. 数据线' },
  'earphone': { phonetic: '/ˈɪrfoʊn/', definition: '【noun】\n1. 耳机\n2. 耳塞' },
  'sunglass': { phonetic: '/ˈsʌnɡlæs/', definition: '【noun】\n1. 太阳镜\n2. 墨镜' },
  'wallet': { phonetic: '/ˈwɑːlɪt/', definition: '【noun】\n1. 钱包\n2. 皮夹' },
  'ring': { phonetic: '/rɪŋ/', definition: '【noun】\n1. 戒指\n2. 环\n3. 铃声' },
  'necklace': { phonetic: '/ˈnekləs/', definition: '【noun】\n1. 项链' },
  'bracelet': { phonetic: '/ˈbreɪslət/', definition: '【noun】\n1. 手链\n2. 镯子' },
  'glove': { phonetic: '/ɡlʌv/', definition: '【noun】\n1. 手套' },
  'scarf': { phonetic: '/skɑːrf/', definition: '【noun】\n1. 围巾\n2. 披肩' },
  'plant': { phonetic: '/plænt/', definition: '【noun】\n1. 植物\n2. 工厂\n【verb】\n1. 种植' },
  'grass': { phonetic: '/ɡræs/', definition: '【noun】\n1. 草\n2. 草坪' },
  'road': { phonetic: '/roʊd/', definition: '【noun】\n1. 道路\n2. 公路' },
  'house': { phonetic: '/haʊs/', definition: '【noun】\n1. 房子\n2. 住宅' },
  'building': { phonetic: '/ˈbɪldɪŋ/', definition: '【noun】\n1. 建筑物\n2. 大楼' },
  'school': { phonetic: '/skuːl/', definition: '【noun】\n1. 学校' },
  'hospital': { phonetic: '/ˈhɑːspɪtəl/', definition: '【noun】\n1. 医院' },
  'hotel': { phonetic: '/hoʊˈtel/', definition: '【noun】\n1. 酒店\n2. 旅馆' },
  'restaurant': { phonetic: '/ˈrestərɑːnt/', definition: '【noun】\n1. 餐厅\n2. 饭店' },
  'bank': { phonetic: '/bæŋk/', definition: '【noun】\n1. 银行\n2. 河岸' },
  'library': { phonetic: '/ˈlaɪbreri/', definition: '【noun】\n1. 图书馆' },
  'park': { phonetic: '/pɑːrk/', definition: '【noun】\n1. 公园\n2. 停车场' },
  'beach': { phonetic: '/biːtʃ/', definition: '【noun】\n1. 海滩\n2. 沙滩' },
  'mountain': { phonetic: '/ˈmaʊntən/', definition: '【noun】\n1. 山\n2. 山脉' },
  'river': { phonetic: '/ˈrɪvər/', definition: '【noun】\n1. 河流\n2. 河' },
  'lake': { phonetic: '/leɪk/', definition: '【noun】\n1. 湖\n2. 湖泊' },
  'ocean': { phonetic: '/ˈoʊʃən/', definition: '【noun】\n1. 海洋\n2. 大海' },
  'island': { phonetic: '/ˈaɪlənd/', definition: '【noun】\n1. 岛屿\n2. 岛' }
}

/**
 * 获取本地离线释义
 */
function getLocalDefinition(word) {
  const lowerWord = word.toLowerCase().trim()
  if (localDictionary[lowerWord]) {
    return localDictionary[lowerWord]
  }
  // 如果本地词典也没有，返回一个通用格式
  return {
    phonetic: `/${word}/`,
    definition: `【noun】\n1. ${word}`
  }
}

/**
 * 使用 AI 生成实用例句
 * @param {string} word - 单词
 * @returns {Promise<string[]>} - 例句数组
 */
export async function fetchAiExamples(word) {
  // 使用内置的实用例句库
  return getBuiltInExamples(word)
}

/**
 * 内置例句库
 */
function getBuiltInExamples(word) {
  const examples = {
    'phone': [
      'I forgot my phone at home today.',
      'She answered the phone quickly.',
      'My phone battery is running low.'
    ],
    'cup': [
      'I drink coffee from a cup every morning.',
      'Could I have a cup of tea, please?',
      'She broke a cup while washing dishes.'
    ],
    'computer': [
      'I use a computer for work every day.',
      'The computer is running slowly.',
      'She turned on the computer to check email.'
    ],
    'book': [
      'I am reading an interesting book.',
      'She borrowed a book from the library.',
      'He forgot his book at home.'
    ],
    'bag': [
      'I packed my bag for the trip.',
      'She lost her bag on the train.',
      'The bag is too heavy to carry.'
    ],
    'water': [
      'I drink eight glasses of water every day.',
      'Please pass me a glass of water.',
      'The water is very cold.'
    ],
    'coffee': [
      'I need a cup of coffee to wake up.',
      'She makes coffee every morning.',
      'The coffee smells great.'
    ],
    'car': [
      'He drives a red car to work.',
      'The car needs to be washed.',
      'She parked the car in the garage.'
    ],
    'bicycle': [
      'I ride my bicycle to school.',
      'The bicycle is new.',
      'He locked the bicycle to the fence.'
    ],
    'dog': [
      'The dog loves to play in the park.',
      'She takes her dog for a walk every morning.',
      'The dog is sleeping under the tree.'
    ],
    'cat': [
      'The cat is sitting on the sofa.',
      'She pet the cat gently.',
      'The cat caught a mouse.'
    ],
    'apple': [
      'An apple a day keeps the doctor away.',
      'I bought fresh apples from the market.',
      'The apple juice is very refreshing.'
    ],
    'banana': [
      'I ate a banana for breakfast.',
      'The banana is ripe and sweet.',
      'She bought some bananas at the store.'
    ],
    'chair': [
      'Please sit on this chair.',
      'He pulled the chair closer to the table.',
      'The chair is very comfortable.'
    ],
    'table': [
      'The book is on the table.',
      'We sat around the dining table.',
      'Please clear the table after dinner.'
    ],
    'bed': [
      'I go to bed at 10 PM.',
      'The bed is very soft and comfortable.',
      'She made the bed this morning.'
    ],
    'door': [
      'Please close the door behind you.',
      'Someone is knocking at the door.',
      'The door is locked.'
    ],
    'window': [
      'Please open the window for fresh air.',
      'The window is broken.',
      'She looked out the window.'
    ],
    'clock': [
      'The clock on the wall shows 3 o\'clock.',
      'I wound the clock yesterday.',
      'The clock is ticking loudly.'
    ],
    'camera': [
      'I took a photo with my camera.',
      'She bought a new camera.',
      'The camera battery is dead.'
    ],
    'key': [
      'I lost my key this morning.',
      'She has the key to the door.',
      'The key is on the table.'
    ],
    'watch': [
      'I wear a watch every day.',
      'She looked at her watch.',
      'The watch is very expensive.'
    ],
    'glasses': [
      'I wear glasses for reading.',
      'She cleaned her glasses.',
      'The glasses are on the table.'
    ],
    'hat': [
      'She wore a hat to protect from the sun.',
      'The hat is too small for me.',
      'He took off his hat.'
    ],
    'shoe': [
      'I bought a new pair of shoes.',
      'The shoes are very comfortable.',
      'She took off her shoes at the door.'
    ],
    'bag': [
      'I packed my bag for the trip.',
      'She lost her bag on the train.',
      'The bag is too heavy.'
    ]
  }

  const lowerWord = word.toLowerCase()
  if (examples[lowerWord]) {
    return examples[lowerWord]
  }

  // 通用例句
  return [
    `The ${word} is very useful in daily life.`,
    `I use the ${word} every day.`,
    `Can you pass me the ${word}?`
  ]
}

/**
 * 使用 MyMemory API 翻译句子（免费，无需API Key）
 */
export async function translateSentence(sentence) {
  if (!sentence) return ''

  try {
    // MyMemory 免费翻译 API
    const response = await fetch(
      `https://api.mymemory.translated.net/get?q=${encodeURIComponent(sentence)}&langpair=en|zh-CN`
    )
    const data = await response.json()
    if (data.responseStatus === 200 && data.responseData) {
      return data.responseData.translatedText
    }
  } catch (error) {
    console.error('翻译失败:', error)
  }

  return '暂无翻译'
}

/**
 * 简单的本地翻译（仅作为后备）
 * 单词替换翻译，质量和准确性较低
 */
const translations = {
  // 通用例句翻译
  'i': '我',
  'you': '你',
  'he': '他',
  'she': '她',
  'it': '它',
  'we': '我们',
  'they': '他们',
  'the': '这个/那个',
  'a': '一个',
  'an': '一个',
  'this': '这个',
  'that': '那个',
  'is': '是',
  'are': '是',
  'was': '是',
  'were': '是',
  'have': '有',
  'has': '有',
  'had': '有',
  'do': '做',
  'does': '做',
  'did': '做',
  'will': '将',
  'would': '会',
  'can': '能',
  'could': '能',
  'should': '应该',
  'may': '可能',
  'might': '可能',
  'must': '必须',
  'need': '需要',
  'want': '想要',
  'like': '喜欢',
  'love': '爱',
  'use': '使用',
  'make': '制作',
  'go': '去',
  'come': '来',
  'see': '看见',
  'know': '知道',
  'think': '认为',
  'take': '拿',
  'get': '得到',
  'give': '给',
  'tell': '告诉',
  'say': '说',
  'let': '让',
  'put': '放',
  'keep': '保持',
  'help': '帮助',
  'play': '玩',
  'run': '跑',
  'walk': '走',
  'eat': '吃',
  'drink': '喝',
  'sleep': '睡觉',
  'wake': '醒来',
  'read': '阅读',
  'write': '写',
  'listen': '听',
  'speak': '说',
  'look': '看',
  'watch': '观看',
  'buy': '买',
  'sell': '卖',
  'pay': '支付',
  'send': '发送',
  'bring': '带来',
  'break': '打破',
  'fix': '修理',
  'wash': '洗',
  'clean': '清洁',
  'open': '打开',
  'close': '关闭',
  'start': '开始',
  'stop': '停止',
  'turn': '转',
  'hold': '握住',
  'cut': '切',
  'build': '建造',
  'carry': '携带',
  'throw': '扔',
  'hit': '击中',
  'hear': '听到',
  'feel': '感觉',
  'love': '爱',
  'meet': '遇见',
  'leave': '离开',
  'call': '打电话',
  'try': '尝试',
  'ask': '问',
  'need': '需要',
  'answer': '回答',
  'remember': '记得',
  'forget': '忘记',
  'find': '找到',
  'lose': '丢失',
  'win': '赢',
  'love': '爱',
  'every': '每个',
  'day': '天',
  'morning': '早上',
  'afternoon': '下午',
  'evening': '晚上',
  'night': '夜晚',
  'today': '今天',
  'tomorrow': '明天',
  'yesterday': '昨天',
  'week': '周',
  'month': '月',
  'year': '年',
  'time': '时间',
  'home': '家',
  'house': '房子',
  'work': '工作',
  'school': '学校',
  'book': '书',
  'cup': '杯子',
  'phone': '手机',
  'computer': '电脑',
  'car': '汽车',
  'table': '桌子',
  'chair': '椅子',
  'bed': '床',
  'door': '门',
  'window': '窗户',
  'water': '水',
  'coffee': '咖啡',
  'tea': '茶',
  'milk': '牛奶',
  'food': '食物',
  'friend': '朋友',
  'family': '家人',
  'mother': '妈妈',
  'father': '爸爸',
  'sister': '姐妹',
  'brother': '兄弟',
  'boy': '男孩',
  'girl': '女孩',
  'man': '男人',
  'woman': '女人',
  'child': '孩子',
  'people': '人们',
  'thing': '东西',
  'stuff': '东西',
  'place': '地方',
  'way': '方式',
  'hand': '手',
  'head': '头',
  'face': '脸',
  'eye': '眼睛',
  'ear': '耳朵',
  'nose': '鼻子',
  'mouth': '嘴',
  'body': '身体',
  'very': '非常',
  'much': '很多',
  'more': '更多',
  'some': '一些',
  'any': '任何',
  'all': '全部',
  'other': '其他',
  'another': '另一个',
  'only': '只有',
  'also': '也',
  'too': '也',
  'well': '好',
  'just': '只是',
  'now': '现在',
  'then': '然后',
  'here': '这里',
  'there': '那里',
  'where': '哪里',
  'when': '什么时候',
  'what': '什么',
  'why': '为什么',
  'how': '怎样',
  'which': '哪个',
  'who': '谁',
  'very': '非常',
  'really': '真的',
  'often': '经常',
  'sometimes': '有时',
  'always': '总是',
  'never': '从不',
  'usually': '通常',
  'quickly': '快速地',
  'slowly': '缓慢地',
  'easily': '容易地',
  'hard': '努力地/硬的',
  'soft': '柔软的',
  'good': '好的',
  'bad': '坏的',
  'big': '大的',
  'small': '小的',
  'large': '大的',
  'long': '长的',
  'short': '短的',
  'tall': '高的',
  'high': '高的',
  'low': '低的',
  'new': '新的',
  'old': '旧的',
  'young': '年轻的',
  'hot': '热的',
  'cold': '冷的',
  'warm': '温暖的',
  'cool': '凉爽的',
  'full': '满的',
  'empty': '空的',
  'right': '正确的/右边',
  'left': '左边的',
  'back': '后面',
  'front': '前面',
  'up': '上',
  'down': '下',
  'in': '里面',
  'out': '外面',
  'on': '上面',
  'off': '关闭',
  'under': '下面',
  'over': '上面',
  'between': '之间',
  'with': '和',
  'without': '没有',
  'for': '为了',
  'from': '从',
  'to': '到',
  'at': '在',
  'by': '通过',
  'about': '关于',
  'after': '之后',
  'before': '之前',
  'again': '再次',
  'once': '一次',
  'twice': '两次',
  'please': '请',
  'thank': '谢谢',
  'sorry': '对不起',
  'yes': '是的',
  'no': '不',
  'ok': '好的',
  'great': '太棒了',
  'nice': '好的',
  'beautiful': '美丽的',
  'wonderful': '精彩的',
  'lovely': '可爱的',
  'pretty': '漂亮的',
  'handsome': '英俊的',
  'expensive': '昂贵的',
  'cheap': '便宜的',
  'free': '免费的',
  'busy': '忙的',
  'free': '空闲的',
  'tired': '累的',
  'happy': '开心的',
  'sad': '悲伤的',
  'angry': '生气的',
  'afraid': '害怕的',
  'surprised': '惊讶的',
  'excited': '兴奋的',
  'boring': '无聊的',
  'interesting': '有趣的',
  'important': '重要的',
  'difficult': '困难的',
  'easy': '容易的',
  'possible': '可能的',
  'impossible': '不可能的',
  'ready': '准备好的',
  'finished': '完成了',
  'broken': '坏了',
  'fixed': '修好了',
  'lost': '丢失了',
  'found': '找到了',
  'wrong': '错误的',
  'mine': '我的',
  'yours': '你的',
  'his': '他的',
  'hers': '她的',
  'ours': '我们的',
  'theirs': '他们的',
  'something': '某物',
  'anything': '任何东西',
  'nothing': '什么都没有',
  'everything': '一切',
  'someone': '某人',
  'anyone': '任何人',
  'no one': '没有人',
  'everyone': '每个人',
  'please': '请',
  'thank you': '谢谢你',
  'you are welcome': '不客气',
  'excuse me': '打扰一下',
  'i am sorry': '对不起',
  'i see': '我明白了',
  'i know': '我知道',
  'i think': '我认为',
  'i want': '我想要',
  'i need': '我需要',
  'i like': '我喜欢',
  'i love': '我爱',
  'i have': '我有',
  'i will': '我将会',
  'i can': '我能',
  'i cannot': '我不能',
  'i do not': '我不',
  'it is': '它是',
  'there is': '有',
  'there are': '有一些',
  'what is': '是什么',
  'what are': '是什么',
  'where is': '在哪里',
  'where are': '在哪里',
  'when is': '什么时候',
  'when are': '什么时候',
  'who is': '是谁',
  'who are': '是谁',
  'how is': '怎么样',
  'how are': '怎么样',
  'how many': '多少',
  'how much': '多少',
  'how old': '多大',
  'how far': '多远',
  'what time': '什么时间',
  'a lot': '很多',
  'a little': '一点',
  'a few': '几个',
  'in the morning': '在早上',
  'in the afternoon': '在下午',
  'in the evening': '在晚上',
  'at night': '在晚上',
  'at home': '在家',
  'at work': '在工作',
  'at school': '在学校',
  'on the table': '在桌子上',
  'on the chair': '在椅子上',
  'in the room': '在房间里',
  'in the house': '在房子里',
  'in the car': '在车里',
  'on the way': '在路上',
  'in front of': '在...前面',
  'behind': '在...后面',
  'next to': '旁边',
  'near': '附近',
  'far from': '远离',
  'kind of': '有点',
  'a bit': '一点',
  'right now': '现在',
  'right away': '立刻',
  'in a minute': '马上',
  'later': '之后',
  'soon': '不久',
  'already': '已经',
  'still': '仍然',
  'not yet': '还没有',
  'over there': '在那里',
  'over here': '在这里',
  'down here': '在这里',
  'up there': '在那里',
  'up here': '在这里',
  'back there': '回那里',
  'back here': '回这里',
  'all the time': '一直',
  'at the same time': '同时',
  'right away': '立刻',
  'for example': '例如',
  'that is why': '这就是为什么',
  'as well': '也',
  'in fact': '实际上',
  'of course': '当然',
  'i see': '我懂了',
  'let me see': '让我想想',
  'i guess': '我猜',
  'i believe': '我相信',
  'i hope': '我希望',
  'i am sure': '我确定',
  'i am afraid': '恐怕',
  'i wonder': '我想知道',
  'it depends': '看情况',
  'it does not matter': '没关系',
  'take care': '保重',
  'good luck': '祝你好运',
  'have fun': '玩得开心',
  'good job': '做得好',
  'well done': '干得好',
  'congratulations': '恭喜',
  'happy birthday': '生日快乐',
  'merry christmas': '圣诞快乐',
  'happy new year': '新年快乐',
  'thank you very much': '非常感谢',
  'i appreciate it': '我很感激',
  'do not mention it': '不客气',
  'that is all': '就这样',
  'that is it': '就这样',
  'i am done': '我做完了',
  'i am finished': '我做完了',
  'that is good': '那很好',
  'that is bad': '那不好',
  'that is great': '那太棒了',
  'that is terrible': '那太可怕了',
  'what a pity': '真可惜',
  'it does not matter': '没关系',
  'no problem': '没问题',
  'my pleasure': '我的荣幸',
  'you are welcome': '不客气',
  'take your time': '慢慢来',
  'no worries': '别担心',
  'cheers': '干杯/谢谢',
  'bye': '再见',
  'goodbye': '再见',
  'see you': '回头见',
  'see you later': '待会儿见',
  'see you soon': '一会儿见',
  'see you tomorrow': '明天见',
  'good night': '晚安',
  'sleep well': '睡个好觉',
  'have a nice day': '祝你有美好的一天',
  'have a good one': '祝你有美好的一天',
  'drive safely': '安全驾驶',
  'be careful': '小心',
  'watch out': '小心',
  'look out': '小心',
  'watch your step': '小心脚下',
  'mind your head': '小心碰头',
  'watch your language': '注意言辞',
  'behave yourself': '规矩点',
  'make yourself at home': '别客气',
  'help yourself': '请自便',
  'make yourself comfortable': '请随意',
  'take a seat': '请坐',
  'sit down': '请坐',
  'stand up': '站起来',
  'come in': '进来',
  'go out': '出去',
  'come here': '过来',
  'go there': '去那里',
  'come on': '快点',
  'hold on': '等一下',
  'wait a moment': '等一下',
  'just a minute': '等一下',
  'one moment': '等一下',
  'half a second': '等一下',
  'in a second': '马上',
  'in a moment': '马上',
  'be right back': '马上回来',
  'i will be back': '我马上回来',
  'i am leaving': '我要走了',
  'i am going': '我走了',
  'i am back': '我回来了',
  'i am here': '我在这里',
  'i am home': '我到家了',
  'long time no see': '好久不见',
  'how have you been': '你最近怎么样',
  'what is new': '有什么新鲜事',
  'what is up': '怎么了',
  'not much': '没什么',
  'nothing much': '没什么',
  'same old': '老样子',
  'so so': '一般',
  'i am fine': '我很好',
  'i am good': '我很好',
  'i am doing well': '我做得很好',
  'i am not bad': '我不坏',
  'i am tired': '我累了',
  'i am busy': '我很忙',
  'i am free': '我有空',
  'i am sick': '我生病了',
  'i am hungry': '我饿了',
  'i am thirsty': '我渴了',
  'i am sleepy': '我想睡觉',
  'i am cold': '我冷',
  'i am hot': '我热',
  'i am right': '我是对的',
  'i am wrong': '我错了',
  'i am late': '我迟到了',
  'i am early': '我早了',
  'i am ready': '我准备好了',
  'i am done': '我做完了',
  'i am going': '我要走了',
  'i am coming': '我来了',
  'i am staying': '我留下',
  'i am leaving': '我走了',
  'i am coming back': '我回来了',
  'i am going home': '我回家了',
  'i am going to bed': '我要睡觉了',
  'i am going to sleep': '我要睡觉了',
  'i am going to work': '我去上班',
  'i am going to school': '我去上学',
  'i am going to the store': '我去商店',
  'i am going to the park': '我去公园',
  'i am going to the gym': '我去健身房',
  'i am going to the movies': '我去看电影',
  'i am going to the restaurant': '我去餐厅',
  'i am going to the beach': '我去海滩',
  'i am going to the mountains': '我去山里',
  'i am going to the city': '我去城市',
  'i am going to the country': '我去乡下',
  'i am going to the farm': '我去农场',
  'i am going to the zoo': '我去动物园',
  'i am going to the museum': '我去博物馆',
  'i am going to the library': '我去图书馆',
  'i am going to the hospital': '我去医院',
  'i am going to the doctor': '我去看医生',
  'i am going to the dentist': '我去看牙医',
  'i am going to the pharmacy': '我去药店',
  'i am going to the bank': '我去银行',
  'i am going to the post office': '我去邮局',
  'i am going to the supermarket': '我去超市',
  'i am going to the mall': '我去商场',
  'i am going to the shop': '我去商店',
  'i am going to the market': '我去市场',
  'i am going to the bakery': '我去面包店',
  'i am going to the coffee shop': '我去咖啡店',
  'i am going to the bar': '我去酒吧',
  'i am going to the club': '我去俱乐部',
  'i am going to the gym': '我去健身房',
  'i am going to the spa': '我去水疗',
  'i am going to the salon': '我去美容院',
  'i am going to the barbershop': '我去理发店',
  'i am going to the gas station': '我去加油站',
  'i am going to the car wash': '我去洗车',
  'i am going to the repair shop': '我去修理店',
  'i am going to the tire shop': '我去轮胎店',
  'i am going to the bike shop': '我去自行车店',
  'i am going to the pet store': '我去宠物店',
  'i am going to the flower shop': '我去花店',
  'i am going to the gift shop': '我去礼品店',
  'i am going to the book store': '我去书店',
  'i am going to the toy store': '我去玩具店',
  'i am going to the electronics store': '我去电子产品店',
  'i am going to the furniture store': '我去家具店',
  'i am going to the clothing store': '我去服装店',
  'i am going to the shoe store': '我去鞋店',
  'i am going to the jewelry store': '我去珠宝店',
  'i am going to the sporting goods store': '我去体育用品店',
  'i am going to the outdoor store': '我去户外用品店',
  'i am going to the drugstore': '我去药店',
  'i am going to the convenience store': '我去便利店',
  'i am going to the department store': '我去百货商店',
  'i am going to the wholesale store': '我去批发店',
  'i am going to the warehouse store': '我去仓储店',
  'i am going to the dollar store': '我去一元店',
  'i am going to the second hand store': '我去二手店',
  'i am going to the antique store': '我去古董店',
  'i am going to the craft store': '我去工艺店',
  'i am going to the fabric store': '我去布料店',
  'i am going to the bead store': '我去珠子店',
  'i am going to the yarn store': '我去毛线店',
  'i am going to the scrapbook store': '我去剪贴簿店',
  'i am going to the party supply store': '我去派对用品店',
  'i am going to the balloon store': '我去气球店',
  'i am going to the costume store': '我去服装店',
  'i am going to the Halloween store': '我去万圣节店',
  'i am going to the Christmas store': '我去圣诞节店',
  'i am going to the Easter store': '我去复活节店',
  'i am going to the Valentine store': '我去情人节店',
  'i am going to the graduation store': '我去毕业店',
  'i am going to the wedding store': '我去婚礼店',
  'i am going to the birthday store': '我去生日店',
  'i am going to the baby shower store': '我去婴儿用品店',
  'i am going to the bridal store': '我去新娘用品店',
  'i am going to the tuxedo shop': '我去礼服店',
  'i am going to the suit shop': '我去西装店',
  'i am going to the dress shop': '我去裙子店',
  'i am going to the boutique': '我去精品店',
  'i am going to the vintage store': '我去复古店',
  'i am going to the consignment shop': '我去寄卖店',
  'i am going to the thrift store': '我去 thrift 店',
  'i am going to the charity shop': '我去慈善店',
  'i am going to the vintage clothing store': '我去复古服装店',
  'i am going to the designer store': '我去设计师店',
  'i am going to the outlet store': '我去折扣店',
  'i am going to the factory store': '我去工厂店',
  'i am going to the sample sale': '我去样品 sale',
  'i am going to the trunk show': '我去 trunk show',
  'i am going to the pop up shop': '我去快闪店',
  'i am going to the flea market': '我去跳蚤市场',
  'i am going to the farmers market': '我去农贸市场',
  'i am going to the swap meet': '我去交换会',
  'i am going to the bazaar': '我去集市',
  'i am going to the fair': '我去博览会',
  'i am going to the exhibition': '我去展览会',
  'i am going to the trade show': '我去 trade show',
  'i am going to the convention': '我去大会',
  'i am going to the conference': '我去会议',
  'i am going to the seminar': '我去研讨会',
  'i am going to the workshop': '我去工作坊',
  'i am going to the class': '我去上课',
  'i am going to the lecture': '我去听讲座',
  'i am going to the presentation': '我去听演讲',
  'i am going to the meeting': '我去开会',
  'i am going to the interview': '我去面试',
  'i am going to the appointment': '我去赴约',
  'i am going to the check up': '我去检查',
  'i am going to the doctor': '我去看病',
  'i am going to the dentist': '我去看牙医',
  'i am going to the eye doctor': '我去看眼科',
  'i am going to the specialist': '我去看专科',
  'i am going to the emergency room': '我去急诊',
  'i am going to the urgent care': '我去急诊',
  'i am going to the pharmacy': '我去药店',
  'i am going to the lab': '我去实验室',
  'i am going to the imaging center': '我去影像中心',
  'i am going to the therapy': '我去治疗',
  'i am going to the counseling': '我去咨询',
  'i am going to the support group': '我去支持小组',
  'i am going to the meeting': '我去开会',
  'i am going to the support meeting': '我去支持会议',
  'i am going to the group session': '我去小组会议',
  'i am going to the one on one': '我去一对一',
  'i am going to the session': '我去开会',
  'i am going to the class': '我去上课',
  'i am going to the course': '我去上课',
  'i am going to the training': '我去培训',
  'i am going to the seminar': '我去研讨会',
  'i am going to the workshop': '我去工作坊',
  'i am going to the conference': '我去会议',
  'i am going to the convention': '我去大会',
  'i am going to the expo': '我去博览会',
  'i am going to the trade show': '我去贸易展',
  'i am going to the fair': '我去展会',
  'i am going to the show': '我去展会',
  'i am going to the exhibition': '我去展览',
  'i am going to the gallery': '我去画廊',
  'i am going to the museum': '我去博物馆',
  'i am going to the art show': '我去艺术展',
  'i am going to the concert': '我去音乐会',
  'i am going to the play': '我去剧院',
  'i am going to the movie': '我去看电影',
  'i am going to the theater': '我去剧院',
  'i am going to the cinema': '我去看电影',
  'i am going to the drive in': '我去免下车影院',
  'i am going to the sporting event': '我去体育赛事',
  'i am going to the game': '我去观看比赛',
  'i am going to the match': '我去观看比赛',
  'i am going to the race': '我去观看比赛',
  'i am going to the tournament': '我去参加锦标赛',
  'i am going to the competition': '我去参加比赛',
  'i am going to the contest': '我去参加竞赛',
  'i am going to the event': '我去参加活动',
  'i am going to the party': '我去参加派对',
  'i am going to the gathering': '我去参加聚会',
  'i am going to the reunion': '我去参加聚会',
  'i am going to the celebration': '我去参加庆祝',
  'i am going to the ceremony': '我去参加仪式',
  'i am going to the graduation': '我去参加毕业典礼',
  'i am going to the wedding': '我去参加婚礼',
  'i am going to the baby shower': '我去参加婴儿派对',
  'i am going to the bridal shower': '我去参加新娘派对',
  'i am going to the birthday party': '我去参加生日派对',
  'i am going to the anniversary party': '我去参加周年派对',
  'i am going to the holiday party': '我去参加节日派对',
  'i am going to the office party': '我去参加办公室派对',
  'i am going to the house warming': '我去参加乔迁派对',
  'i am going to the going away party': '我去参加送别派对',
  'i am going to the welcome party': '我去参加欢迎派对',
  'i am going to the farewell party': '我去参加告别派对',
  'i am going to the christmas party': '我去参加圣诞派对',
  'i am going to the new years party': '我去参加新年派对',
  'i am going to the halloween party': '我去参加万圣节派对',
  'i am going to the easter party': '我去参加复活节派对',
  'i am going to the thanksgiving party': '我去参加感恩节派对',
  'i am going to the fourth of july party': '我去参加美国独立日派对',
  'i am going to the super bowl party': '我去参加超级碗派对',
  'i am going to the oscars party': '我去参加奥斯卡派对',
  'i am going to the emmy party': '我去参加艾美奖派对',
  'i am going to the grammy party': '我去参加格莱美派对',
  'i am going to the golden globes party': '我去参加金球奖派对',
  'i am going to the academy awards party': '我去参加奥斯卡派对',
  'i am going to the watching party': '我去参加观看派对',
  'i am going to the premiere': '我去参加首映',
  'i am going to the opening': '我去参加开幕式',
  'i am going to the reception': '我去参加招待会',
  'i am going to the mixer': '我去参加交流会',
  'i am going to the networking event': '我去参加社交活动',
  'i am going to the business event': '我去参加商业活动',
  'i am going to the corporate event': '我去参加企业活动',
  'i am going to the company event': '我去参加公司活动',
  'i am going to the team building event': '我去参加团队建设活动',
  'i am going to the retreat': '我去参加静修',
  'i am going to the getaway': '我去参加小长假',
  'i am going to the vacation': '我去度假',
  'i am going to the trip': '我去旅行',
  'i am going to the journey': '我去旅行',
  'i am going to the tour': '我去旅游',
  'i am going to the excursion': '我去远足',
  'i am going to the adventure': '我去冒险',
  'i am going to the expedition': '我去探险',
  'i am going to the safari': '我去狩猎',
  'i am going to the cruise': '我去邮轮',
  'i am going to the sail': '我去航海',
  'i am going to the boat ride': '我去乘船',
  'i am going to the ferry ride': '我去乘渡轮',
  'i am going to the train ride': '我去坐火车',
  'i am going to the bus ride': '我去坐公共汽车',
  'i am going to the car ride': '我开车去',
  'i am going to the bike ride': '我去骑自行车',
  'i am going to the motorcycle ride': '我去骑摩托车',
  'i am going to the scooter ride': '我去骑 scooter',
  'i am going to the skateboard ride': '我去滑滑板',
  'i am going to the rollerblade ride': '我去滚轴溜冰',
  'i am going to the ice skate ride': '我去滑冰',
  'i am going to the ski ride': '我去滑雪',
  'i am going to the snowboard ride': '我去滑雪板',
  'i am going to the sled ride': '我去坐雪橇',
  'i am going to the sleigh ride': '我去坐雪橇',
  'i am going to the hayride': '我去坐干草车',
  'i am going to the pony ride': '我去骑马',
  'i am going to the horse back riding': '我去骑马',
  'i am going to the camel ride': '我去骑骆驼',
  'i am going to the elephant ride': '我去骑大象',
  'i am going to the hot air balloon ride': '我去坐热气球',
  'i am going to the helicopter ride': '我去坐直升机',
  'i am going to the airplane ride': '我坐飞机',
  'i am going to the jet ski ride': '我去骑水上摩托',
  'i am going to the para sailing': '我去帆伞运动',
  'i am going to the scuba diving': '我去潜水',
  'i am going to the snorkeling': '我去浮潜',
  'i am going to the surfing': '我去冲浪',
  'i am going to the swimming': '我去游泳',
  'i am going to the fishing': '我去钓鱼',
  'i am going to the boating': '我去划船',
  'i am going to the kayaking': '我去划皮划艇',
  'i am going to the canoeing': '我去划独木舟',
  'i am going to the rowing': '我去划船',
  'i am going to the sailing': '我去帆船',
  'i am going to the wind surfing': '我去帆板冲浪',
  'i am going to the water skiing': '我去滑水',
  'i am going to the jet skiing': '我去水上摩托',
  'i am going to the tubing': '我去充气筒漂流',
  'i am going to the white water rafting': '我去激流漂流',
  'i am going to the river rafting': '我去河流漂流',
  'i am going to the ocean rafting': '我去海洋漂流',
  'i am going to the banana boat ride': '我去坐香蕉船',
  'i am going to the pontoon ride': '我去坐平底船',
  'i am going to the house boat stay': '我去住船屋',
  'i am going to the cabin stay': '我去住小木屋',
  'i am going to the yurt stay': '我去住蒙古包',
  'i am going to the tent stay': '我去露营',
  'i am going to the camping': '我去露营',
  'i am going to the glamping': '我去豪华露营',
  'i am going to the caravan stay': '我去住大篷车',
  'i am going to the rv stay': '我去住房车',
  'i am going to the trailer stay': '我去住拖车',
  'i am going to the mobile home stay': '我去住活动房屋',
  'i am going to the timeshare': '我去分时度假',
  'i am going to the hotel stay': '我住酒店',
  'i am going to the motel stay': '我住汽车旅馆',
  'i am going to the hostel stay': '我住青年旅社',
  'i am going to the bed and breakfast': '我住民宿',
  'i am going to the guest house': '我住客房',
  'i am going to the inn stay': '我住客栈',
  'i am going to the lodge stay': '我住山林小屋',
  'i am going to the resort stay': '我住度假村',
  'i am going to the spa resort': '我去水疗度假村',
  'i am going to the beach resort': '我去海滩度假村',
  'i am going to the ski resort': '我去滑雪度假村',
  'i am going to the golf resort': '我去高尔夫度假村',
  'i am going to the theme park resort': '我去主题公园度假村',
  'i am going to the all inclusive resort': '我去全包度假村',
  'i am going to the luxury resort': '我去豪华度假村',
  'i am going to the boutique resort': '我去精品度假村',
  'i am going to the eco resort': '我去生态度假村',
  'i am going to the sustainable resort': '我去可持续度假村',
  'i am going to the green resort': '我去绿色度假村',
  'i am going to the wellness resort': '我去健康度假村',
  'i am going to the health resort': '我去健康度假村',
  'i am going to the medical resort': '我去医疗度假村',
  'i am going to the dental resort': '我去牙科度假村',
  'i am going to the cosmetic resort': '我去美容度假村',
  'i am going to the weight loss resort': '我去减肥度假村',
  'i am going to the fitness resort': '我去健身度假村',
  'i am going to the yoga resort': '我去瑜伽度假村',
  'i am going to the meditation resort': '我去冥想度假村',
  'i am going to the spiritual resort': '我去精神度假村',
  'i am going to the holistic resort': '我去整体度假村',
  'i am going to the养生 resort': '我去养生度假村',
  'i am going to the中医 resort': '我去中医度假村',
  'i am going to the acupuncture resort': '我去针灸度假村',
  'i am going to the massage resort': '我去按摩度假村',
  'i am going to the aromatherapy resort': '我去芳香疗法度假村',
  'i am going to the herbal resort': '我去草药度假村',
  'i am going to the naturopathy resort': '我去自然疗法度假村',
  'i am going to the ayurveda resort': '我去阿育吠陀度假村',
  'i am going to the yoga retreat': '我去瑜伽静修',
  'i am going to the meditation retreat': '我去冥想静修',
  'i am going to the spiritual retreat': '我去精神静修',
  'i am going to the yoga meditation retreat': '我去瑜伽冥想静修',
  'i am going to the wellness retreat': '我去健康静修',
  'i am going to the health retreat': '我去健康静修',
  'i am going to the fitness retreat': '我去健身静修',
  'i am going to the detox retreat': '我去排毒静修',
  'i am going to the cleanse retreat': '我去清洁静修',
  'i am going to the juice retreat': '我去果汁静修',
  'i am going to the raw food retreat': '我去生食静修',
  'i am going to the vegetarian retreat': '我去素食静修',
  'i am going to the vegan retreat': '我去纯素静修',
  'i am going to the organic retreat': '我去有机静修',
  'i am going to the farm retreat': '我去农场静修',
  'i am going to the vineyard retreat': '我去葡萄园静修',
  'i am going to the winery retreat': '我去酒庄静修',
  'i am going to the brewery retreat': '我去啤酒厂静修',
  'i am going to the distillery retreat': '我去酿酒厂静修',
  'i am going to the wine tasting retreat': '我去品酒静修',
  'i am going to the beer tasting retreat': '我去品啤酒静修',
  'i am going to the whiskey tasting retreat': '我去威士忌品酒静修',
  'i am going to the cocktail retreat': '我去鸡尾酒静修',
  'i am going to the culinary retreat': '我去美食静修',
  'i am going to the cooking retreat': '我去烹饪静修',
  'i am going to the baking retreat': '我去烘焙静修',
  'i am going to the pastry retreat': '我去糕点静修',
  'i am going to the chocolate retreat': '我去巧克力静修',
  'i am going to the wine and food retreat': '我去美食美酒静修',
  'i am going to the gastronomy retreat': '我去美食学静修',
  'i am going to the culinary arts retreat': '我去烹饪艺术静修',
  'i am going to the restaurant retreat': '我去餐厅静修',
  'i am going to the chef retreat': '我去厨师静修',
  'i am going to the foodie retreat': '我去美食家静修',
  'i am going to the gourmet retreat': '我去美食静修',
  'i am going to the epicurean retreat': '我去美食家静修',
  'i am going to the taste retreat': '我去品味静修',
  'i am going to the flavor retreat': '我去风味静修',
  'i am going to the seasoning retreat': '我去调味静修',
  'i am going to the spice retreat': '我去香料静修',
  'i am going to the herb retreat': '我去香草静修',
  'i am going to the seasoning cooking retreat': '我去调味烹饪静修',
  'i am going to the farm to table retreat': '我从农场到餐桌静修',
  'i am going to the organic retreat': '我去有机静修',
  'i am going to the sustainable eating retreat': '我去可持续饮食静修',
  'i am going to the healthy eating retreat': '我去健康饮食静修',
  'i am going to the diet retreat': '我去饮食静修',
  'i am going to the weight loss retreat': '我去减肥静修',
  'i am going to the fitness retreat': '我去健身静修',
  'i am going to the exercise retreat': '我去锻炼静修',
  'i am going to the physical therapy retreat': '我去物理治疗静修',
  'i am going to the rehabilitation retreat': '我去康复静修',
  'i am going to the recovery retreat': '我去康复静修',
  'i am going to the healing retreat': '我去疗养静修',
  'i am going to the medical retreat': '我去医疗静修',
  'i am going to the health retreat': '我去健康静修',
  'i am going to the wellness retreat': '我去健康静修',
  'i am going to the spa retreat': '我去水疗静修',
  'i am going to the beauty retreat': '我去美容静修',
  'i am going to the cosmetic retreat': '我去美容静修',
  'i am going to the aesthetic retreat': '我去审美静修',
  'i am going to the anti aging retreat': '我去抗衰老静修',
  'i am going to the longevity retreat': '我去长寿静修',
  'i am going to the preventive medicine retreat': '我去预防医学静修',
  'i am going to the holistic health retreat': '我去整体健康静修',
  'i am going to the integrative medicine retreat': '我去综合医学静修',
  'i am going to the complementary medicine retreat': '我去补充医学静修',
  'i am going to the alternative medicine retreat': '我去替代医学静修',
  'i am going to the traditional medicine retreat': '我去传统医学静修',
  'i am going to the chinese medicine retreat': '我去中医静修',
  'i am going to the ayurvedic retreat': '我去阿育吠陀静修',
  'i am going to the naturopathic retreat': '我去自然疗法静修',
  'i am going to the herbal medicine retreat': '我去草药医学静修',
  'i am going to the homeopathic retreat': '我去顺势疗法静修',
  'i am going to the acupuncture retreat': '我去针灸静修',
  'i am going to the acupressure retreat': '我去指压静修',
  'i am going to the reflexology retreat': '我去反射疗法静修',
  'i am going to the massage therapy retreat': '我去按摩疗法静修',
  'i am going to the swedish massage retreat': '我去瑞典按摩静修',
  'i am going to the deep tissue retreat': '我去深层组织静修',
  'i am going to the hot stone retreat': '我去热石静修',
  'i am going to the aromatherapy retreat': '我去芳香疗法静修',
  'i am going to the essential oils retreat': '我去精油静修',
  'i am going to the yoga therapy retreat': '我去瑜伽疗法静修',
  'i am going to the pilates retreat': '我去普拉提静修',
  'i am going to the tai chi retreat': '我去太极拳静修',
  'i am going to the qigong retreat': '我去气功静修',
  'i am going to the meditation retreat': '我去冥想静修',
  'i am going to the mindfulness retreat': '我去正念静修',
  'i am going to the zen retreat': '我去禅静修',
  'i am going to the buddhism retreat': '我去佛教静修',
  'i am going to the spirituality retreat': '我去精神静修',
  'i am going to the religious retreat': '我去宗教静修',
  'i am going to the church retreat': '我去教堂静修',
  'i am going to the monastery retreat': '我去修道院静修',
  'i am going to the convent retreat': '我去女修道院静修',
  'i am going to the pilgrimage': '我去朝圣',
  'i am going to the spiritual journey': '我去精神旅程',
  'i am going to the sacred journey': '我去神圣旅程',
  'i am going to the religious journey': '我去宗教旅程',
  'i am going to the faith journey': '我去信仰旅程',
  'i am going to the spiritual pilgrimage': '我去精神朝圣',
  'i am going to the holy land pilgrimage': '我去圣地朝圣',
  'i am going to the mecca pilgrimage': '我去麦加朝圣',
  'i am going to the rome pilgrimage': '我去罗马朝圣',
  'i am going to the compostela pilgrimage': '我去圣地亚哥朝圣',
  'i am going to the spiritual excursion': '我去精神远足',
  'i am going to the sacred excursion': '我去神圣远足',
  'i am going to the holy excursion': '我去圣地远足',
  'i am going to the religious excursion': '我去宗教远足',
  'i am going to the faith excursion': '我去信仰远足',
  'i am going to the spiritual trip': '我去精神旅行',
  'i am going to the sacred trip': '我去神圣旅行',
  'i am going to the holy trip': '我去圣地旅行',
  'i am going to the religious trip': '我去宗教旅行',
  'i am going to the faith trip': '我去信仰旅行',
  'i am going to the spiritual tour': '我去精神之旅',
  'i am going to the sacred tour': '我去神圣之旅',
  'i am going to the holy tour': '我去圣地之旅',
  'i am going to the religious tour': '我去宗教之旅',
  'i am going to the faith tour': '我去信仰之旅',
  'i am going to the spiritual voyage': '我去精神航行',
  'i am going to the sacred voyage': '我去神圣航行',
  'i am going to the holy voyage': '我去圣地航行',
  'i am going to the religious voyage': '我去宗教航行',
  'i am going to the faith voyage': '我去信仰航行',
  'i am going to the spiritual adventure': '我去精神冒险',
  'i am going to the sacred adventure': '我去神圣冒险',
  'i am going to the holy adventure': '我去圣地冒险',
  'i am going to the religious adventure': '我去宗教冒险',
  'i am going to the faith adventure': '我去信仰冒险',
  'i am going to the spiritual exploration': '我去精神探索',
  'i am going to the sacred exploration': '我去神圣探索',
  'i am going to the holy exploration': '我去圣地探索',
  'i am going to the religious exploration': '我去宗教探索',
  'i am going to the faith exploration': '我去信仰探索',
  'i am going to the spiritual discovery': '我去精神发现',
  'i am going to the sacred discovery': '我去神圣发现',
  'i am going to the holy discovery': '我去圣地发现',
  'i am going to the religious discovery': '我去宗教发现',
  'i am going to the faith discovery': '我去信仰发现',
  'i am going to the spiritual quest': '我去精神探索',
  'i am going to the sacred quest': '我去神圣探索',
  'i am going to the holy quest': '我去圣地探索',
  'i am going to the religious quest': '我去宗教探索',
  'i am going to the faith quest': '我去信仰探索',
  'i am going to the spiritual seeking': '我去精神寻求',
  'i am going to the sacred seeking': '我去神圣寻求',
  'i am going to the holy seeking': '我去圣地寻求',
  'i am going to the religious seeking': '我去宗教寻求',
  'i am going to the faith seeking': '我去信仰寻求',
  'i am going to the spiritual searching': '我去精神搜索',
  'i am going to the sacred searching': '我去神圣搜索',
  'i am going to the holy searching': '我去圣地搜索',
  'i am going to the religious searching': '我去宗教搜索',
  'i am going to the faith searching': '我去信仰搜索',
  'i am going to the spiritual learning': '我去精神学习',
  'i am going to the sacred learning': '我去神圣学习',
  'i am going to the holy learning': '我去圣地学习',
  'i am going to the religious learning': '我去宗教学习',
  'i am going to the faith learning': '我去信仰学习',
  'i am going to the spiritual study': '我去精神研究',
  'i am going to the sacred study': '我去神圣研究',
  'i am going to the holy study': '我去圣地研究',
  'i am going to the religious study': '我去宗教研究',
  'i am going to the faith study': '我去信仰研究',
  'i am going to the spiritual education': '我去精神教育',
  'i am going to the sacred education': '我去神圣教育',
  'i am going to the holy education': '我去圣地教育',
  'i am going to the religious education': '我去宗教教育',
  'i am going to the faith education': '我去信仰教育',
  'i am going to the spiritual growth': '我去精神成长',
  'i am going to the sacred growth': '我去神圣成长',
  'i am going to the holy growth': '我去圣地成长',
  'i am going to the religious growth': '我去宗教成长',
  'i am going to the faith growth': '我去信仰成长',
  'i am going to the spiritual development': '我去精神发展',
  'i am going to the sacred development': '我去神圣发展',
  'i am going to the holy development': '我去圣地发展',
  'i am going to the religious development': '我去宗教发展',
  'i am going to the faith development': '我去信仰发展',
  'i am going to the spiritual awakening': '我去精神觉醒',
  'i am going to the sacred awakening': '我去神圣觉醒',
  'i am going to the holy awakening': '我去圣地觉醒',
  'i am going to the religious awakening': '我去宗教觉醒',
  'i am going to the faith awakening': '我去信仰觉醒',
  'i am going to the spiritual enlightenment': '我去精神启蒙',
  'i am going to the sacred enlightenment': '我去神圣启蒙',
  'i am going to the holy enlightenment': '我去圣地启蒙',
  'i am going to the religious enlightenment': '我去宗教启蒙',
  'i am going to the faith enlightenment': '我去信仰启蒙',
  'i am going to the spiritual liberation': '我去精神解放',
  'i am going to the sacred liberation': '我去神圣解放',
  'i am going to the holy liberation': '我去圣地解放',
  'i am going to the religious liberation': '我去宗教解放',
  'i am going to the faith liberation': '我去信仰解放',
  'i am going to the spiritual freedom': '我去精神自由',
  'i am going to the sacred freedom': '我去神圣自由',
  'i am going to the holy freedom': '我去圣地自由',
  'i am going to the religious freedom': '我去宗教自由',
  'i am going to the faith freedom': '我去信仰自由',
  'i am going to the spiritual peace': '我去精神平静',
  'i am going to the sacred peace': '我去神圣平静',
  'i am going to the holy peace': '我去圣地平静',
  'i am going to the religious peace': '我去宗教平静',
  'i am going to the faith peace': '我去信仰平静',
  'i am going to the spiritual harmony': '我去精神和谐',
  'i am going to the sacred harmony': '我去神圣和谐',
  'i am going to the holy harmony': '我去圣地和谐',
  'i am going to the religious harmony': '我去宗教和谐',
  'i am going to the faith harmony': '我去信仰和谐',
  'i am going to the spiritual balance': '我去精神平衡',
  'i am going to the sacred balance': '我去神圣平衡',
  'i am going to the holy balance': '我去圣地平衡',
  'i am going to the religious balance': '我去宗教平衡',
  'i am going to the faith balance': '我去信仰平衡',
  'i am going to the spiritual equilibrium': '我去精神平衡',
  'i am going to the sacred equilibrium': '我去神圣平衡',
  'i am going to the holy equilibrium': '我去圣地平衡',
  'i am going to the religious equilibrium': '我去宗教平衡',
  'i am going to the faith equilibrium': '我去信仰平衡',
  'i am going to the spiritual stability': '我去精神稳定',
  'i am going to the sacred stability': '我去神圣稳定',
  'i am going to the holy stability': '我去圣地稳定',
  'i am going to the religious stability': '我去宗教稳定',
  'i am going to the faith stability': '我去信仰稳定',
  'i am going to the spiritual centeredness': '我去精神中心',
  'i am going to the sacred centeredness': '我去神圣中心',
  'i am going to the holy centeredness': '我去圣地中心',
  'i am going to the religious centeredness': '我去宗教中心',
  'i am going to the faith centeredness': '我去信仰中心',
  'i am going to the spiritual grounding': '我去精神接地',
  'i am going to the sacred grounding': '我去神圣接地',
  'i am going to the holy grounding': '我去圣地接地',
  'i am going to the religious grounding': '我去宗教接地',
  'i am going to the faith grounding': '我去信仰接地',
  'i am going to the spiritual rootedness': '我去精神扎根',
  'i am going to the sacred rootedness': '我去神圣扎根',
  'i am going to the holy rootedness': '我去圣地扎根',
  'i am going to the religious rootedness': '我去宗教扎根',
  'i am going to the faith rootedness': '我去信仰扎根',
  'i am going to the spiritual foundation': '我去精神基础',
  'i am going to the sacred foundation': '我去神圣基础',
  'i am going to the holy foundation': '我去圣地基础',
  'i am going to the religious foundation': '我去宗教基础',
  'i am going to the faith foundation': '我去信仰基础',
  'i am going to the spiritual base': '我去精神基础',
  'i am going to the sacred base': '我去神圣基础',
  'i am going to the holy base': '我去圣地基础',
  'i am going to the religious base': '我去宗教基础',
  'i am going to the faith base': '我去信仰基础',
  'i am going to the spiritual core': '我去精神核心',
  'i am going to the sacred core': '我去神圣核心',
  'i am going to the holy core': '我去圣地核心',
  'i am going to the religious core': '我去宗教核心',
  'i am going to the faith core': '我去信仰核心',
  'i am going to the spiritual essence': '我去精神本质',
  'i am going to the sacred essence': '我去神圣本质',
  'i am going to the holy essence': '我去圣地本质',
  'i am going to the religious essence': '我去宗教本质',
  'i am going to the faith essence': '我去信仰本质',
  'i am going to the spiritual heart': '我去精神心脏',
  'i am going to the sacred heart': '我去神圣心脏',
  'i am going to the holy heart': '我去圣地心脏',
  'i am going to the religious heart': '我去宗教心脏',
  'i am going to the faith heart': '我去信仰心脏',
  'i am going to the spiritual soul': '我去精神灵魂',
  'i am going to the sacred soul': '我去神圣灵魂',
  'i am going to the holy soul': '我去圣地灵魂',
  'i am going to the religious soul': '我去宗教灵魂',
  'i am going to the faith soul': '我去信仰灵魂',
  'i am going to the spiritual spirit': '我去精神精神',
  'i am going to the sacred spirit': '我去神圣精神',
  'i am going to the holy spirit': '我去圣灵',
  'i am going to the religious spirit': '我去宗教精神',
  'i am going to the faith spirit': '我去信仰精神'
}

// 后备翻译函数（当 API 不可用时使用简单的单词替换）
function simpleTranslate(sentence) {
  if (!sentence) return ''
  let result = sentence.toLowerCase()
  Object.keys(translations).forEach(word => {
    const regex = new RegExp(`\\b${word}\\b`, 'gi')
    result = result.replace(regex, translations[word])
  })
  return result.replace(/\s+/g, ' ').trim() || '暂无翻译'
}
